name: Scheduled work Print-time
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-22.04
    steps:
      - name: Print current time
        run: date