name: Manual Run Embacy monitoring
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run app
        env:
          TEST_GREEN: "true"
        run: go run embacy-monitoring
